"""
pipeline/rag.py
---------------
Stage 5: Retrieval-Augmented Generation via Anthropic Claude API

Takes:
  - The user's query
  - The top-K retrieved chunks (from ChromaDB semantic search)
  - The Anthropic API key

Sends a real API call to Claude and returns the actual LLM response.

NOTHING is hardcoded or templated — the answer is generated by Claude
based on the actual retrieved content.
"""

from __future__ import annotations

import anthropic

# Default model — fast and cost-efficient
DEFAULT_MODEL = "claude-3-5-haiku-20241022"
MAX_TOKENS    = 1024


def build_prompt(query: str, chunks: list[dict]) -> str:
    """
    Construct the RAG prompt from retrieved chunks + user query.

    The prompt instructs Claude to:
      1. Answer using ONLY the provided context
      2. Cite which source/chunk the answer comes from
      3. Acknowledge if the context is insufficient
    """
    if not chunks:
        context_block = "[No relevant memories found in your knowledge base.]"
    else:
        parts = []
        for i, chunk in enumerate(chunks, 1):
            src   = chunk["metadata"].get("source", "unknown")
            score = chunk.get("final_score", chunk.get("similarity", "?"))
            parts.append(
                f"[Memory {i} | Source: {src} | Relevance: {score:.2f}]\n{chunk['text']}"
            )
        context_block = "\n\n---\n\n".join(parts)

    prompt = f"""You are the AI Digital Memory Guardian — a personal assistant that helps users recall and synthesize information from their own documents and notes.

The user has asked:
"{query}"

Below are the most relevant memories retrieved from their personal knowledge base (ordered by relevance):

=== RETRIEVED MEMORIES ===
{context_block}
=== END OF MEMORIES ===

Instructions:
- Answer the user's question using ONLY the information in the retrieved memories above.
- Be specific and cite which memory/source you're drawing from.
- If the retrieved memories don't contain enough information to answer, say so clearly.
- Keep your answer concise but complete.
- Highlight any particularly relevant details.

Your answer:"""

    return prompt


def generate_answer(
    query: str,
    chunks: list[dict],
    api_key: str,
    model: str = DEFAULT_MODEL,
) -> tuple[str, dict]:
    """
    Call Claude with the RAG prompt and return the generated answer.

    Parameters
    ----------
    query : str
        The user's natural language question.
    chunks : list[dict]
        Retrieved chunks from ChromaDB (with text, metadata, scores).
    api_key : str
        Anthropic API key.
    model : str
        Claude model identifier.

    Returns
    -------
    tuple[str, dict]
        (answer_text, usage_stats)
        usage_stats contains: input_tokens, output_tokens
    """
    client = anthropic.Anthropic(api_key=api_key)
    prompt = build_prompt(query, chunks)

    # Real API call — no mocking, no caching, actual Claude response
    response = client.messages.create(
        model=model,
        max_tokens=MAX_TOKENS,
        messages=[
            {"role": "user", "content": prompt}
        ],
    )

    answer      = response.content[0].text
    usage_stats = {
        "input_tokens":  response.usage.input_tokens,
        "output_tokens": response.usage.output_tokens,
        "model":         response.model,
    }

    return answer, usage_stats


def generate_local_summary(query: str, chunks: list[dict]) -> tuple[str, dict]:
    """
    Generate an intelligent, offline extractive synthesis without any external API calls or credits.
    Analyzes top retrieved chunks, extracts high-relevance sentences, and formats a coherent digest.
    """
    if not chunks:
        return "No relevant memories found in your knowledge base for this query.", {
            "model": "Local Extractive Engine (Offline / Zero Cost)",
            "input_tokens": 0,
            "output_tokens": 0,
        }

    import re
    query_words = set(re.findall(r"\w+", query.lower()))
    
    synthesized_sections = []
    total_sentences = 0

    for i, c in enumerate(chunks[:3], 1):
        src = c.get("metadata", {}).get("source", "Memory Document")
        score = c.get("final_score", c.get("similarity", 0.0))
        text = c.get("text", "").strip()

        # Split into sentences
        raw_sentences = re.split(r"(?<=[.!?])\s+", text)
        scored_sents = []
        for s in raw_sentences:
            s_clean = s.strip()
            if len(s_clean) < 15:
                continue
            s_words = set(re.findall(r"\w+", s_clean.lower()))
            overlap = len(s_words.intersection(query_words))
            scored_sents.append((overlap, s_clean))

        # Pick top sentences from this chunk
        scored_sents.sort(key=lambda x: x[0], reverse=True)
        top_sents = [s[1] for s in scored_sents[:2]] if scored_sents else [text[:200] + "..."]

        sentence_bullets = "\n".join(f"  - {s}" for s in top_sents)
        synthesized_sections.append(
            f"**From {src}** *(relevance {score * 100:.1f}%)*:\n{sentence_bullets}"
        )
        total_sentences += len(top_sents)

    header = f"### Synthesized Memory Overview for: \"{query}\"\n\n"
    body = "\n\n".join(synthesized_sections)
    footer = f"\n\n*Extracted {total_sentences} key passages directly from local vector store without external API calls.*"

    answer = header + body + footer
    usage = {
        "model": "Local Extractive Engine (Offline / Zero Cost)",
        "input_tokens": 0,
        "output_tokens": len(answer.split()),
    }
    return answer, usage

