"""
pipeline/rag.py
---------------
Stage 5: Retrieval-Augmented Generation via Anthropic Claude API

Takes:
  - The user's query
  - The top-K retrieved chunks (from ChromaDB semantic search)
  - The Anthropic API key

Sends a real API call to Claude and returns the actual LLM response.

NOTHING is hardcoded or templated — the answer is generated by Claude
based on the actual retrieved content.
"""

from __future__ import annotations

import anthropic

# Default model — fast and cost-efficient
DEFAULT_MODEL = "claude-3-5-haiku-20241022"
MAX_TOKENS    = 1024


def build_prompt(query: str, chunks: list[dict]) -> str:
    """
    Construct the RAG prompt from retrieved chunks + user query.

    The prompt instructs Claude to:
      1. Answer using ONLY the provided context
      2. Cite which source/chunk the answer comes from
      3. Acknowledge if the context is insufficient
    """
    if not chunks:
        context_block = "[No relevant memories found in your knowledge base.]"
    else:
        parts = []
        for i, chunk in enumerate(chunks, 1):
            src   = chunk["metadata"].get("source", "unknown")
            score = chunk.get("final_score", chunk.get("similarity", "?"))
            parts.append(
                f"[Memory {i} | Source: {src} | Relevance: {score:.2f}]\n{chunk['text']}"
            )
        context_block = "\n\n---\n\n".join(parts)

    prompt = f"""You are the AI Digital Memory Guardian — a personal assistant that helps users recall and synthesize information from their own documents and notes.

The user has asked:
"{query}"

Below are the most relevant memories retrieved from their personal knowledge base (ordered by relevance):

=== RETRIEVED MEMORIES ===
{context_block}
=== END OF MEMORIES ===

Instructions:
- Answer the user's question using ONLY the information in the retrieved memories above.
- Be specific and cite which memory/source you're drawing from.
- If the retrieved memories don't contain enough information to answer, say so clearly.
- Keep your answer concise but complete.
- Highlight any particularly relevant details.

Your answer:"""

    return prompt


def generate_answer(
    query: str,
    chunks: list[dict],
    api_key: str,
    model: str = DEFAULT_MODEL,
) -> tuple[str, dict]:
    """
    Call Claude with the RAG prompt and return the generated answer.

    Parameters
    ----------
    query : str
        The user's natural language question.
    chunks : list[dict]
        Retrieved chunks from ChromaDB (with text, metadata, scores).
    api_key : str
        Anthropic API key.
    model : str
        Claude model identifier.

    Returns
    -------
    tuple[str, dict]
        (answer_text, usage_stats)
        usage_stats contains: input_tokens, output_tokens
    """
    client = anthropic.Anthropic(api_key=api_key)
    prompt = build_prompt(query, chunks)

    # Real API call — no mocking, no caching, actual Claude response
    response = client.messages.create(
        model=model,
        max_tokens=MAX_TOKENS,
        messages=[
            {"role": "user", "content": prompt}
        ],
    )

    answer      = response.content[0].text
    usage_stats = {
        "input_tokens":  response.usage.input_tokens,
        "output_tokens": response.usage.output_tokens,
        "model":         response.model,
    }

    return answer, usage_stats
